// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	sysadmin "api/internal/handler/sys/admin"
	"api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CheckUrl},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/sys/admin/add",
					Handler: sysadmin.AdminAddHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/sys/admin/login",
				Handler: sysadmin.AdminLoginHandler(serverCtx),
			},
		},
	)
}
